### ISSUE TITLE
Create new endpoint for getting all hobbies of all participants

### ISSUE THREAD

**Issue by N-Shar-ma** [N-Shar-ma/FOSS-Weekend-Participants-API#10]
Create a new endpoint which returns an array with the hobbies of ALL the participants in `profiles.json`, but ensure no hobby is mentioned twice. For example if 2 profiles share a common hobby "dancing", it should only appear in the array once. The URL should be http://localhost:3000/profiles/hobbies.

Make sure to add a link to your new endpoint in the homepage public/index.html as well to complete the PR, and add a screenshot to your PR showing the url and data returned (refer to the example screenshot in https://github.com/N-Shar-ma/FOSS-Weekend-Participants-API/issues/1)

**Comment by Animeshz** [comment]
Hello! I can work on this too, may I be assigned?

**Comment by Animeshz** [comment]
Um, am I missing something?

**Comment by N-Shar-ma** [comment]
@Animeshz Sorry I missed your initial comment. Please be a little patient, there are lots of PRs for us to review!

**Comment by delClg** [comment]
Can I work on this issue?

<img width="507" alt="1" src="https://user-images.githubusercontent.com/96474794/157894111-247c8852-fdb1-42c5-8862-5df4eef801a6.png">
<img width="694" alt="2" src="https://user-images.githubusercontent.com/96474794/157894120-d1279b9f-638f-497f-9fb7-66fba6cf58df.png">

**Comment by KarthikS373** [comment]
Ma'am can I get this assigned?

**Comment by N-Shar-ma** [comment]
@delClg yes, you may!

**Comment by KarthikS373** [comment]
Ma'am can I have this issue

**Comment by N-Shar-ma** [comment]
@KarthikS373 Sure!

**Comment by Vikrantpalle** [comment]
Ma'am I want to take this issue up.
