### ISSUE TITLE
Create new endpoint for getting profiles by age

### ISSUE THREAD

**Issue by N-Shar-ma** [N-Shar-ma/FOSS-Weekend-Participants-API#2]
Create a new endpoint which returns data for ALL (not just 1) the participants who are of the requested age. The URL should be something like http://localhost:3000/profiles?age=19. Ensure you use a query parameter (not path parameter like for roll number) for age!

Make sure to add a link to your new endpoint in the homepage `public/index.html` as well to complete the PR, and add a screenshot to your PR showing the url and data returned (refer to the example screenshot  in #1)

**Comment by Animeshz** [comment]
I think I can do this, can you please assign it to me :smiley:

**Comment by Vikrantpalle** [comment]
Ma'am I want to take this task up.

**Comment by delClg** [comment]
Can I be assigned this issue?

<img width="677" alt="1" src="https://user-images.githubusercontent.com/96474794/157881716-8837ebde-cc88-419f-971e-851eeb423dd2.png">
<img width="704" alt="2" src="https://user-images.githubusercontent.com/96474794/157881730-50fc7b42-c458-4c1a-87b4-1422ecd3148f.png">
<img width="566" alt="3" src="https://user-images.githubusercontent.com/96474794/157881740-125b7226-410c-4cb3-b2ab-75b504d8103a.png">
<img width="740" alt="4" src="https://user-images.githubusercontent.com/96474794/157881752-8b04d74d-046c-41aa-80ab-80a44ce2c9b2.png">
<img width="749" alt="6" src="https://user-images.githubusercontent.com/96474794/157881781-967d4192-b5a2-49e6-80ef-4abef277e0ed.png">

**Comment by N-Shar-ma** [comment]
@delClg Go ahead!

**Comment by Ilikepizza2** [comment]
Ma'am is this issue still up?
If yes then please assign it to me.

**Comment by KarthikS373** [comment]
Ma'am is this still available ?

**Comment by N-Shar-ma** [comment]
@KarthikS373 Good find! Yes it is :)

**Comment by KarthikS373** [comment]
Can I get assigned?

**Comment by N-Shar-ma** [comment]
Yes yes, that's what I meant.
