### ISSUE TITLE
Create new endpoint for getting profiles by hobby

### ISSUE THREAD

**Issue by N-Shar-ma** [N-Shar-ma/FOSS-Weekend-Participants-API#3]
Create a new endpoint which returns data for ALL (not just 1) the participants who have the requested hobby in their array of hobbies. The URL should be something like http://localhost:3000/profiles?hobby=reading. Ensure you use a query parameter (not path parameter like for roll number) for hobby!

Make sure to add a link to your new endpoint in the homepage `public/index.html` as well to complete the PR, and add a screenshot to your PR showing the url and data returned (refer to the example screenshot  in #1)

**Comment by Animeshz** [comment]
I can work on this, please assign it to me, won't forget adding it to the `public/index.html` this time :)

**Comment by Vikrantpalle** [comment]
Ma'am I am interested in taking this up.

**Comment by delClg** [comment]
Can I work on this issue?

<img width="730" alt="1" src="https://user-images.githubusercontent.com/96474794/157884321-f7429c40-ba25-4549-bbdf-59723f8ad8d9.png">
<img width="611" alt="2" src="https://user-images.githubusercontent.com/96474794/157884331-a25cc851-bc1b-45f8-aee0-7801a9a2005a.png">
<img width="692" alt="3" src="https://user-images.githubusercontent.com/96474794/157884349-41740cf1-0314-42e8-b9dd-a3afd133d5ba.png">

**Comment by N-Shar-ma** [comment]
@delClg Yes, make the PR!
