### ISSUE TITLE
Create new endpoint for getting roll numbers of all participants

### ISSUE THREAD

**Issue by N-Shar-ma** [N-Shar-ma/FOSS-Weekend-Participants-API#9]
Create a new endpoint which returns an array with the roll numbers of ALL the participants in `profiles.json`. The URL should be http://localhost:3000/profiles/roll-numbers. 

Make sure to add a link to your new endpoint in the homepage `public/index.html` as well to complete the PR, and add a screenshot to your PR showing the url and data returned (refer to the example screenshot  in #1)

**Comment by Ilikepizza2** [comment]
If it's still up then please assign it to me.

**Comment by N-Shar-ma** [comment]
@Ilikepizza2 Sure it is, you're the first asking to be assigned. Go ahead

**Comment by delClg** [comment]
Can I work on this issue?
<img width="722" alt="13" src="https://user-images.githubusercontent.com/96474794/157888369-dcfbf684-bcb5-4662-9380-a75c56547d6a.png">
<img width="463" alt="12" src="https://user-images.githubusercontent.com/96474794/157888382-18fee2d2-f852-4162-93e7-39b19a084923.png">
<img width="693" alt="11" src="https://user-images.githubusercontent.com/96474794/157888389-67d17ad6-fe8a-412e-9883-7ba52aa92f20.png">

**Comment by KarthikS373** [comment]
Ma'am can I have this

**Comment by N-Shar-ma** [comment]
> Ma'am can I have this

Yes, go ahead

**Comment by Vikrantpalle** [comment]
Are there any spots left?

**Comment by N-Shar-ma** [comment]
@Vikrantpalle Sorry, 3 successful PRs have already been made. Hope to see you fix other issues!
